### ISSUE TITLE
The Xamarin Android Device Manage page return 404

### ISSUE THREAD

**Issue by xiaogaoming** [MicrosoftDocs/xamarin-docs.zh-cn#4] opened 2018-06-24 15:34 UTC
When click the Xamarin Android Device Manager, it return the 404 - https://docs.microsoft.com/zh-cn/xamarin/android/get-started/installation/android-emulator/device-manager.md.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 440a1c4c-31dd-5120-fd35-5ac1ffa287b9
* Version Independent ID: 14c189a9-9a57-472d-2f4a-0d47f40ce536
* Content: [Android 仿真器设置 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/android/get-started/installation/android-emulator/)
* Content Source: [docs/android/get-started/installation/android-emulator/index.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/android/get-started/installation/android-emulator/index.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment] 2018-06-25 17:01
Hi @xiaogaoming, thanks for the feedback!  Unfortunately, it looks like the redirect is not working. I've added task to our backlog to investigate the cause and get it fixed.

**Comment by mgmclemore** [comment] 2018-06-25 19:02
Until the redirect is fixed, you can access the topic here: https://docs.microsoft.com/zh-cn/xamarin/android/get-started/installation/android-emulator/device-manager. Hope this helps!

**Comment by mgmclemore** [comment] 2018-06-27 22:54
The redirect is fixed.

**Comment by mgmclemore** [comment] 2018-07-30 18:57
This issue can be closed.

**Comment by mgmclemore** [comment] 2018-07-31 19:07
(I can't close it or reassign it.)

**Comment by CeciAc** [comment] 2018-08-07 21:26
Thank you @mgmclemore 
I'm closing this issue since it was already solved on your side

Kind regards,
Microsoft DOCS International Team

**Closed by CeciAc** 2018-08-07 21:26 UTC
Labels: Source Issue
